export const CASTING_ROLE_ACTION_TYPES = {
    GET_CASTING_ROLE_START: 'castingRole/GET_CASTING_ROLE_START',
    GET_CASTING_ROLE_SUCCESS: 'castingRole/GET_CASTING_ROLE_SUCCESS',
    GET_CASTING_ROLE_FAILED: 'castingRole/GET_CASTING_ROLE_FAILED',
}