export const CASTINGS_ACTION_TYPES = {
    GET_CASTINGS_START: 'castings/GET_CASTINGS_START',
    GET_CASTINGS_SUCCESS: 'castings/GET_CASTINGS_SUCCESS',
    GET_CASTINGS_FAILED: 'castings/GET_CASTINGS_FAILED',
}