export const CASTING_ACTION_TYPES = {
    GET_CASTING_START: 'casting/GET_CASTING_START',
    GET_CASTING_SUCCESS: 'casting/GET_CASTING_SUCCESS',
    GET_CASTING_FAILED: 'casting/GET_CASTING_FAILED',
    TOGGLE_EDIT_IMAGE: 'casting/TOGGLE_EDIT_IMAGE',
    REMOVE_CASTING_ROLE_FROM_CASTING: 'casting/REMOVE_CASTING_ROLE_FROM_CASTING',
    ADD_CASTING_ROLE_TO_CASTING: 'casting/ADD_CASTING_ROLE_TO_CASTING',
    UPDATE_CASTING: 'casting/UPDATE_CASTING'
}